[package]
name = "yangest-core"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Magnus Thoäng <magnusthoang@gmail.com>"]

[dependencies]
clap = { version = "4", default-features = false, features = ["std"] }
indexmap = "2.14.0"
inventory = "0.3"
nom = "8.0.0"
quick-xml = "0.39.3"
regexml = "0.2.2"
